"""Build reviewed source-attested expansion; stable IDs never depend on row order."""
from pathlib import Path
import hashlib, json, unicodedata

root = Path(__file__).parent
base = json.loads((root/'site/data.js').read_text().split('=',1)[1].strip().rstrip(';'))
def normalized(s):
    return ' '.join(unicodedata.normalize('NFC',s).lower().strip().rstrip('.!?').split())

known = {normalized(w['wolof']) for w in base['lexicon']}
entries=[]
skipped=[]
pos_names={'verb':'verbo','stative-verb':'verbo di stato','noun':'nome','adverb':'avverbio','pronoun':'pronome','interjection':'interiezione'}
for filename, kind in [('corpus-expansion.tsv','word'),('corpus-phrases.tsv','phrase')]:
    for line in (root/filename).read_text().splitlines():
        if not line or line.startswith('#'): continue
        cols=line.split('|')
        if kind=='word': cat,page,pos,form,meaning=cols
        else: cat,page,form,meaning=cols;pos='expression'
        form=unicodedata.normalize('NFC',form)
        key=normalized(form)
        if key in known:
            skipped.append(form)
            continue
        known.add(key)
        uid='pcsn-'+hashlib.sha256(key.encode()).hexdigest()[:12]
        ref=f'PDF p. {page}'
        entries.append({'id':uid,'category':cat,'wolof':form,'lemma':form,'italian':meaning,'kind':kind,
                        'pos':pos_names.get(pos,'espressione'),'level':None,'frequency':None,
                        'meanings':meaning.split('; '),'tags':[cat,'espansione-2026-10'],
                        'source':'PC-SN-2012','ref':ref,'variants':[],'note':'', 'examples':[],
                        'orthography':{'canonical':form,'note':''},
                        'provenance':[{'sourceId':'PC-SN-2012','ref':ref,'status':'source-checked',
                                       'checkedOn':'2026-10-07','translationLanguage':'it',
                                       'translationReview':'editorial; not native-speaker reviewed'}]})

# Examples are complete attested phrases, with independent source references.
for w in entries:
    if w['kind']!='word': continue
    tokens=normalized(w['wolof']).split()
    for p in [*base['lexicon'],*entries]:
        if p['kind']!='phrase': continue
        pt=normalized(p['wolof']).split()
        if any(pt[i:i+len(tokens)]==tokens for i in range(len(pt)-len(tokens)+1)):
            w['examples'].append({'wolof':p['wolof'],'italian':p['italian'],'sourceId':p['source'],'ref':p['ref']})
    w['examples']=w['examples'][:3]

pack={'id':'pcsn-practical-2026-10','schemaVersion':1,'title':'Lessico pratico Peace Corps Senegal',
      'reviewNotes':'Forms and meanings checked against the cited PDF. Italian translations are editorial. No frequency claims or native-speaker certification.',
      'entries':entries}
(root/'site/lexicon-packs.js').write_text('// Source-attested expansion; generated by build-corpus.py.\nwindow.WOLOF_PACKS = '+json.dumps([pack],ensure_ascii=False,indent=2)+';\n')
report={'before':len(base['lexicon']),'added':len(entries),'after':len(base['lexicon'])+len(entries),
        'words':sum(e['kind']=='word' for e in entries),'phrases':sum(e['kind']=='phrase' for e in entries),
        'withExamples':sum(bool(e['examples']) for e in entries),'skippedDuplicateForms':skipped,
        'byCategory':{m['id']:sum(e['category']==m['id'] for e in entries) for m in base['modules']}}
(root/'corpus-expansion-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report,ensure_ascii=False,indent=2))
